### PR TITLE
Generalize  `TwoBandPhotosyntheticallyActiveRadiation` kernel to allow curvilinear grids

### LINKED ISSUE #119: Light attenuation model does not work on lat/lon grids
Light attenuation model does not work on lat/lon grids because `xnode` is defined differently for each. I imagine this may have been fixed recently in Oceananigans so will just be a case of updating the use of the `xnode` function.

### PR DESCRIPTION
**Pull request by jagoosw**
Not sure this is the most efficient way todo this, but since `xnode` is defiend differedntly for different grid types this is by far the easiest fix. The alternative would be to define `xnode(i, grid, lx, ly, lz)` for RectilinearGrids. Perhaps that solution would be better.

Closes #119

### CODE REVIEW

**Comment by jagoosw** [comment]
Probably should add some tests on Lat/lon grids

**Comment by navidcy** [comment]
What do you mean by

> but since `xnode` is defined differently for different grid types this is by far the easiest fix

?

**Comment by navidcy** [comment]
```Julia
xnode(i, j, k, grid, ℓx, ℓy, ℓz)
```

should work for _all_ grids. If the above is not true then we should fix it in Oceananigans.

Note that `xnode(s)` will return the zonal coordinate (e.g. in meters), not the grid's native x-coordinate which can be degrees for some grids.

File: src/Light/2band.jl [hunk 1]
```diff
@@ -1,7 +1,7 @@
 @kernel function update_TwoBandPhotosyntheticallyActiveRadiation!(PAR, grid, P, surface_PAR, t, PAR_model) 
     i, j = @index(Global, NTuple)
 
-    x, y = xnode(i, grid, Center()), ynode(j, grid, Center())
+    x, y = @inbounds xnodes(grid, Center(), Center(), Center())[i], ynodes(grid, Center(), Center(), Center())[j]
```
Comment (navidcy) [inline src/Light/2band.jl:4]: not sure if `k=1` is what we want here, but how about:
```suggestion
    x = xnode(i, j, 1, grid, Center(), Center(), Center())
    y = ynode(i, j, 1, grid, Center(), Center(), Center())
```

Comment (glwagner) [reply src/Light/2band.jl:4]: Note that for general curvilinear grids, the nodes depend on both `i, j`. So you probably want to use @navidcy's suggestion.

All current grids (and for the forseeable future) are independent of `k` so it's ok to take `k=1`. This makes a "thin spherical shell" approximation for the ocean.

**Comment by jagoosw** [comment]
Thank you both @navidcy @glwagner . I'm not sure exactly what I've got confused by, I think it was trying to do `xnode(i, j, grid...` rather than with `i, j, k`. I'll apply these suggestions and see if it works.

I was trying to run one of the ClimaOcean examples with a BGC model which initially wasn't working because the light just had `xnode(i, grid...`, and then I think I just fixed it wrong.

**Comment by navidcy** [comment]
Note that ClimaOcean might need some updating!

**Comment by jagoosw** [comment]
It does work now

> Note that ClimaOcean might need some updating!

I did have to remove some compat entries to install OceanBioME with it but it seems to be running fine with Oceananigans 0.83.0

File: src/Boundaries/Sediments/simple_multi_G.jl [hunk 2]
```diff
@@ -90,7 +90,7 @@ function SimpleMultiG(grid;
                                            D = -1.3349, 
                                            E = 0.1826, 
                                            F = - 0.0143),
-                      depth = abs(znode(1, grid, Face())),
+                      depth = abs(znodes(grid, Face())[1]),
```
Comment (navidcy) [inline src/Boundaries/Sediments/simple_multi_G.jl:93]: `znodes` is user-facing and available as soon as you call `using Oceananigans` so I changed  it here.
this is only called once so it doesn't matter if it's not the most efficient way

File: src/Models/Individuals/SLatissima.jl
Comment (navidcy) [inline src/Models/Individuals/SLatissima.jl:1]: shall we delete commented code? it's unclear why it's there..
```
    #nodes, weights, normfactor = @inbounds get_nearest_nodes(x, y, z, grid, (Center(), Center(), Center()))
    #@unroll for (n, weight) in enumerate(weights)
```

Comment (jagoosw) [reply src/Models/Individuals/SLatissima.jl:1]: Oh yeah, not sure why that's still there

**Comment by jagoosw** [comment]
I've just thought, it's probably more convenient for a user if the surface PAR is in the grid native coordinates, for example, if doing a global simulation data is going to be in lat/lon coordinates. Using `Oceananigans.Grids.node` would be the appropriate thing to use here then right?

**Comment by navidcy** [comment]
```Julia
node(i, j, k, grid, ℓx, ℓy, ℓz)
```
will return a 1-, 2-, or 3- tuple with the native coordinates of the grid. (1-, 2-, or 3-tuple depending if any of the coordinates are Flat).

**Comment by jagoosw** [comment]
> ```julia
> node(i, j, k, grid, ℓx, ℓy, ℓz)
> ```
> 
> will return a 1-, 2-, or 3- tuple with the native coordinates of the grid. (1-, 2-, or 3-tuple depending if any of the coordinates are Flat).

Oh yeah I mean to fix this

**Comment by navidcy** [comment]
hm... I think what you did won't work... because you seem to assume the `node` will return a 3-tuple but it won't necessarily do that

**Comment by navidcy** [comment]
So I'm not sure what you are trying to do so I can't be very specific.
But how about this, is this helpful?
```Julia
locs = node(i, j, k, grid, Center(), Center(), Center())

value = surface_PAR(loss...)
```

This way you don't unfold the tuple but just pass it to the `surface_PAR` as a tuple and use `...` to unpack it then?

**Comment by jagoosw** [comment]
I just checked and it seems to work on flat dimensions always returning a 3-tuple, as long as the locations are all not `nothing` because that's what the different length results are dispatched on:

https://github.com/CliMA/Oceananigans.jl/blob/92791a962c9096746301cdb888a3050e32c4a58b/src/Grids/latitude_longitude_grid.jl#L624-L634

**Comment by jagoosw** [comment]
> So I'm not sure what you are trying to do so I can't be very specific. But how about this, is this helpful?
> 
> ```julia
> locs = node(i, j, k, grid, Center(), Center(), Center())
> 
> value = surface_PAR(loss...)
> ```
> 
> This way you don't unfold the tuple but just pass it to the `surface_PAR` as a tuple and use `...` to unpack it then?

I guess this would work although we currently have `surface_PAR` as a function of x and y only, but if this doesn't work we can change that to include z

**Comment by navidcy** [comment]
> I just checked and it seems to work on flat dimensions always returning a 3-tuple, as long as the locations are all not `nothing` because that's what the different length results are dispatched on:
> 
> https://github.com/CliMA/Oceananigans.jl/blob/92791a962c9096746301cdb888a3050e32c4a58b/src/Grids/latitude_longitude_grid.jl#L624-L634

Hm... But this, e.g.,
https://github.com/CliMA/Oceananigans.jl/blob/92791a962c9096746301cdb888a3050e32c4a58b/src/Grids/latitude_longitude_grid.jl#L629
is a 2-tuple.

**Comment by navidcy** [comment]
> > So I'm not sure what you are trying to do so I can't be very specific. But how about this, is this helpful?
> > ```julia
> > locs = node(i, j, k, grid, Center(), Center(), Center())
> > 
> > value = surface_PAR(loss...)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way you don't unfold the tuple but just pass it to the `surface_PAR` as a tuple and use `...` to unpack it then?
> 
> I guess this would work although we currently have `surface_PAR` as a function of x and y only, but if this doesn't work we can change that to include z

Sorry, ignore my suggestion then.

Perhaps I just don't know what you are trying to do and I was assuming things.

Let's restart: Yes, to get the coordinates of the grid at `i, j, k` then `node(i,j, k, grid,...)` will do the job. :)

**Comment by jagoosw** [comment]
> > I just checked and it seems to work on flat dimensions always returning a 3-tuple, as long as the locations are all not `nothing` because that's what the different length results are dispatched on:
> > https://github.com/CliMA/Oceananigans.jl/blob/92791a962c9096746301cdb888a3050e32c4a58b/src/Grids/latitude_longitude_grid.jl#L624-L634
> 
> Hm... But this, e.g., https://github.com/CliMA/Oceananigans.jl/blob/92791a962c9096746301cdb888a3050e32c4a58b/src/Grids/latitude_longitude_grid.jl#L629 is a 2-tuple.

Since we're always giving the locs as Center/Center/Center won't it always use the first method though? I guess it uses the others if you were to e.g. do `locations(velocity field)` which would return a nothing location on the flat dimension, and then use the function?

**Comment by navidcy** [comment]
> Since we're always giving the locs as Center/Center/Center won't it always use the first method though? I guess it uses the others if you were to e.g. do `locations(velocity field)` which would return a nothing location on the flat dimension, and then use the function?

True! My bad...

**Comment by navidcy** [comment]
should we add a test?

**Comment by jagoosw** [comment]
I've changed the light test to test on different grids and models now, I don't think we need the other tests todo this since the others just test the properties of the bgc model components and their ability to work in different grids etc. should be being tested in the Oceananigans tests right?

I think maybe I should add a test that the particle tendencies and sediment models work across all model types. Although again their ability to function should be caught by the Oceananigans tests now. Perhaps I should test their combinations since that's an issue I found recently.

**Comment by jagoosw** [comment]
I forgot I hadn't pushed the sediment model fixes. I've just made this PR  #121 which has them so I think we should merge these tests and fixes, then look at adding more sediment model tests in that PR.

File: test/test_light.jl [hunk 3]
```diff
@@ -38,5 +40,22 @@ grid = RectilinearGrid(size=(1,1,2), extent=(1,1,2))
 
     results_PAR = convert(Array, model.biogeochemistry.light_attenuation_model.field)[1, 1, 1:2]
 
-    @test all(results_PAR .≈ reverse(expected_PAR))
+    return all(results_PAR .≈ reverse(expected_PAR))
+end
+
+archs = (CPU(), )
+
+@testset "Light attenuaiton model" begin
```
Comment (navidcy) [inline test/test_light.jl:48]:
```suggestion
@testset "Light attenuation model" begin 
```

File: test/test_light.jl [hunk 4]
```diff
@@ -1,22 +1,24 @@
...
+                            surface_phytosynthetically_active_radiation = (x, y, t) -> 100.0)
 
-    model = NonhydrostaticModel(; grid, 
-                                  biogeochemistry = LOBSTER(; grid,
-                                                              light_attenuation_model = TwoBandPhotosyntheticallyActiveRadiation(; grid),
-                                                              surface_phytosynthetically_active_radiation = (x, y, t) -> 100.0))
-    Pᵢ(x,y,z) = 2.5 + z
+    model = model_type(; grid, 
+                         biogeochemistry,
+                         tracers = unique((required_biogeochemical_tracers(biogeochemistry)..., :T, :S))) # because hydrostatic free surface will request T and S and some BGC models will too
```
Comment (navidcy) [inline test/test_light.jl:14]:
```suggestion
                         tracers = unique((required_biogeochemical_tracers(biogeochemistry)..., :T, :S))) # because hydrostatic free surface model will request T and S and some BGC models will too
```

**Review by navidcy — APPROVED** [review]
lgtm
